version: '3.8'

services:
  mysql:
    build: ./mysql
    container_name: cine_mysql
    environment:
      MYSQL_ROOT_PASSWORD: contrasenyaRoot
      MYSQL_DATABASE: cine
      MYSQL_USER: usuario1
      MYSQL_PASSWORD: contrasenyaUsuario1
    volumes:
      - ./mysql/cine.sql:/docker-entrypoint-initdb.d/cine.sql
    ports:
      - "3306:3306"
    networks:
      - cine_network

  src:
    build: ./src
    container_name: cine_src
    ports:
      - "8080:80"
    networks:
      - cine_network
    depends_on:
      - mysql

networks:
  cine_network:
    driver: bridge